"""Footer about band, babypips style: logo, socials, one bold line and a short paragraph.

Run after build_portal.py. Idempotent: re-running replaces the existing band.
"""
from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
PREFIX='rex'
NAME='REX TRADING SIGNAL'
LOGO='/assets/rex-mark.png'
LEAD='REX Trading Signal helps new traders run the market like a business instead of a guessing game, in plain words that will not put you to sleep.'
COPY=('We cover gold, forex and crypto through the numbers any owner would track, costs, risk, written records '
      'and a weekly review, in plain language with examples you can copy straight into your own journal. '
      'We are also a community of traders who support each other day after day in the market.')
SOCIALS=[('telegram','https://t.me/rextrading_gold','REX Trading Signal on Telegram'),
         ('youtube','https://www.youtube.com/channel/UCqwjPkS27s3TZf0ruMZQSHw','REX Trading Signal on YouTube'),
         ('instagram','https://www.instagram.com/rextradingsignalss','REX Trading Signal on Instagram'),
         ('facebook','https://www.facebook.com/rextradingsignal','REX Trading Signal on Facebook')]

ICONS={
 'telegram':'M9.04 15.47 8.7 20.2c.48 0 .69-.21.94-.46l2.25-2.15 4.67 3.42c.86.47 1.47.22 1.7-.79l3.08-14.44c.3-1.26-.46-1.76-1.29-1.45L1.9 9.86c-1.23.48-1.21 1.17-.21 1.48l4.6 1.43 10.68-6.73c.5-.33.96-.15.58.18z',
 'youtube':'M23.5 6.9a3 3 0 0 0-2.12-2.13C19.5 4.25 12 4.25 12 4.25s-7.5 0-9.38.52A3 3 0 0 0 .5 6.9C0 8.79 0 12 0 12s0 3.21.5 5.1a3 3 0 0 0 2.12 2.13c1.88.52 9.38.52 9.38.52s7.5 0 9.38-.52a3 3 0 0 0 2.12-2.13C24 15.21 24 12 24 12s0-3.21-.5-5.1ZM9.6 15.57V8.43L15.82 12 9.6 15.57Z',
 'instagram':'M12 2.16c3.2 0 3.58.01 4.85.07 1.17.05 1.8.25 2.23.41.56.22.96.48 1.38.9.42.42.68.82.9 1.38.16.42.36 1.06.41 2.23.06 1.27.07 1.65.07 4.85s-.01 3.58-.07 4.85c-.05 1.17-.25 1.8-.41 2.23-.22.56-.48.96-.9 1.38-.42.42-.82.68-1.38.9-.42.16-1.06.36-2.23.41-1.27.06-1.65.07-4.85.07s-3.58-.01-4.85-.07c-1.17-.05-1.8-.25-2.23-.41-.56-.22-.96-.48-1.38-.9-.42-.42-.68-.82-.9-1.38-.16-.42-.36-1.06-.41-2.23-.06-1.27-.07-1.65-.07-4.85s.01-3.58.07-4.85c.05-1.17.25-1.8.41-2.23.22-.56.48-.96.9-1.38.42-.42.82-.68 1.38-.9.42-.16 1.06-.36 2.23-.41 1.27-.06 1.65-.07 4.85-.07M12 0C8.74 0 8.33.01 7.05.07c-1.28.06-2.15.26-2.91.56a5.88 5.88 0 0 0-2.13 1.38A5.88 5.88 0 0 0 .63 4.14c-.3.76-.5 1.63-.56 2.91C.01 8.33 0 8.74 0 12s.01 3.67.07 4.95c.06 1.28.26 2.15.56 2.91a5.88 5.88 0 0 0 1.38 2.13 5.88 5.88 0 0 0 2.13 1.38c.76.3 1.63.5 2.91.56C8.33 23.99 8.74 24 12 24s3.67-.01 4.95-.07c1.28-.06 2.15-.26 2.91-.56a6.13 6.13 0 0 0 3.51-3.51c.3-.76.5-1.63.56-2.91.06-1.28.07-1.69.07-4.95s-.01-3.67-.07-4.95c-.06-1.28-.26-2.15-.56-2.91a5.88 5.88 0 0 0-1.38-2.13A5.88 5.88 0 0 0 19.86.63c-.76-.3-1.63-.5-2.91-.56C15.67.01 15.26 0 12 0Zm0 5.84A6.16 6.16 0 1 0 18.16 12 6.16 6.16 0 0 0 12 5.84ZM12 16a4 4 0 1 1 4-4 4 4 0 0 1-4 4Zm7.85-10.4a1.44 1.44 0 1 1-1.44-1.44 1.44 1.44 0 0 1 1.44 1.44Z',
 'facebook':'M24 12.07C24 5.4 18.63 0 12 0S0 5.4 0 12.07C0 18.1 4.39 23.1 10.12 24v-8.44H7.08v-3.49h3.04V9.41c0-3.02 1.79-4.69 4.53-4.69 1.31 0 2.68.24 2.68.24v2.96h-1.51c-1.49 0-1.95.93-1.95 1.89v2.26h3.32l-.53 3.49h-2.79V24C19.61 23.1 24 18.1 24 12.07Z'}

def icon(kind):
 return f'<svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" focusable="false"><path fill="currentColor" d="{ICONS[kind]}"/></svg>'

def band():
 links=''.join(f'<a class="{PREFIX}-about-social-link" href="{u}" aria-label="{l}" target="_blank" rel="noopener">{icon(k)}</a>' for k,u,l in SOCIALS)
 return ('<section class="rex-about" aria-label="About REX Trading Signal"><div class="rex-about-inner">'
  f'<div class="rex-about-head"><a class="rex-about-brand" href="/" translate="no">'
  f'<img class="rex-about-logo" src="{LOGO}" width="104" height="58" alt="{NAME}" loading="lazy"></a>'
  f'<div class="rex-about-social">{links}</div></div>'
  f'<p class="rex-about-lead">{LEAD}</p><p class="rex-about-copy">{COPY}</p></div></section>')

CSS='''/* Footer about band, babypips style. Generated by scripts/about_band.py */
.rex-about{margin:0 0 30px}
.rex-about-inner{border:1px solid rgba(255,255,255,.18);border-radius:14px;padding:22px 24px;max-width:780px}
.rex-about-head{display:flex;align-items:center;gap:20px;flex-wrap:wrap;margin-bottom:14px}
.rex-about-brand{display:inline-flex;align-items:center;background:#fff;border-radius:10px;padding:8px 14px;text-decoration:none}
.rex-about-logo{width:auto;height:34px;max-width:130px;object-fit:contain;display:block}
.rex-about-social{display:inline-flex;align-items:center;gap:15px}
.rex-about-social-link{display:inline-flex;color:#fff;opacity:.72;transition:opacity .15s ease,color .15s ease}
.rex-about-social-link:hover,.rex-about-social-link:focus-visible{opacity:1;color:#ff5a60}
.rex-about-lead{font-weight:700;margin:0 0 10px;line-height:1.55;color:#fff}
.rex-about-copy{margin:0;line-height:1.7;color:#acbbca}
@media(max-width:600px){.rex-about-inner{padding:18px}.rex-about-head{gap:14px}.rex-about-name{font-size:1rem}}
'''

BAND_RE=re.compile(r'<section class="rex-about".*?</section>',re.S)
LOCKUP_RE=re.compile(r'<div class="brand">REX.*?</div>\s*',re.S)
TAGLINE_RE=re.compile(r'(?!x)x')
LEGACY_TAGLINE_RE=re.compile(r'(?!x)x')

def patch(text):
 text=BAND_RE.sub('',text)
 m=re.search(r'<footer[^>]*>',text)
 if not m:return text
 head,tail=text[:m.start()],text[m.start():]
 # the band carries the wordmark, so drop the older duplicate on legacy pages
 tail=LOCKUP_RE.sub('',tail,count=1)
 if '<div class="footer-columns">' in tail:
  tail=tail.replace('<div class="footer-columns">',band()+'<div class="footer-columns">',1)
 else:
  mm=re.match(r'<footer[^>]*>\s*<div class="wrap">\s*',tail)
  if mm:tail=tail[:mm.end()]+band()+tail[mm.end():]
  else:tail=tail[:m.end()-m.start()]+band()+tail[m.end()-m.start():]
 text=head+tail
 if '/assets/about.css' not in text and '</head>' in text:
  text=text.replace('</head>','<link rel="stylesheet" href="/assets/about.css"></head>',1)
 return text

def apply_about():
 (ROOT/'assets/about.css').write_text(CSS)
 changed=0
 for p in ROOT.rglob('*.html'):
  if '.git' in p.parts or 'scripts' in p.parts:continue
  s=p.read_text()
  if '<footer' not in s:continue
  new=patch(s)
  if new!=s:p.write_text(new);changed+=1
 return changed

if __name__=='__main__':print('About band on pages:',apply_about())
