#!/usr/bin/env python3
"""Generate REX's static learning and tools portal; keep daily blog publishing separate."""
from pathlib import Path
import json,html,re,xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]
def read(p):return (ROOT/p).read_text()
def e(s):return html.escape(str(s),quote=True)
lessons=json.loads(read('content/academy.json'));terms=json.loads(read('content/glossary.json'));articles=json.loads(read('articles/_danh-sach.json'))
articlemap={Path(a['url']).stem:a for a in articles};lessonmap={a['slug']:a for a in lessons}
TG='https://t.me/+CR21qcOU0QI4ZDg9';CONTACT='https://t.me/Rextrading_gold'
navgroups=[('Markets',[('Market overview','/markets/'),('Forex snapshot','/markets/forex/'),('Currency strength','/markets/currency-strength/'),('Currency volatility','/markets/volatility/'),('Top movers','/markets/movers/'),('Forex heatmap','/markets/heatmap/'),('Crypto snapshot','/markets/crypto/'),('Crypto strength','/markets/crypto-strength/'),('Crypto volatility','/markets/crypto-volatility/'),('Crypto heatmap','/markets/crypto-heatmap/')]),('Trading',[('All trading articles','/trading/'),('Trade ideas','/trading/trade-ideas/'),('Technical analysis','/trading/technical-analysis/'),('Psychology','/trading/psychology/'),('Trading systems','/trading/systems/'),('Crypto guides','/crypto/guides/')]),('Learn Forex',[('Forex & gold academy','/learn/forex/'),('Forex glossary','/glossary/'),('Forex quizzes','/quizzes/'),('My learning','/my-learning/')]),('Learn Crypto',[('Crypto academy','/learn/crypto/'),('Crypto glossary','/crypto/glossary/'),('Crypto quizzes','/crypto/quizzes/'),('Crypto guides','/crypto/guides/')]),('Tools',[('All tools','/tools/'),('Position size','/tools/position-size/'),('Pip value','/tools/pip-value/'),('Pivot points','/tools/pivot-points/'),('Gain & loss','/tools/gain-loss/'),('Risk / reward','/tools/risk-reward/'),('Currency converter','/tools/currency-converter/'),('Currency correlation','/tools/currency-correlation/'),('Market hours','/tools/market-hours/'),('Risk appetite worksheet','/tools/risk-on-risk-off/'),('Regulator directory','/tools/regulators/')])]
NAV='<header class="portal-header"><div class="portal-shell portal-masthead"><a class="portal-logo" href="/" aria-label="REX Trading Signal home">RE<span>X</span><small>TRADING SIGNAL</small></a><p class="portal-tagline">Learn the process. Protect your capital.</p><div class="portal-actions"><a href="/my-learning/">My learning</a><a class="rex-button" href="'+TG+'">Join free on Telegram</a></div></div><div class="portal-shell portal-nav-control"><button class="portal-menu-toggle" aria-controls="rex-primary-nav" aria-expanded="false" hidden>Browse sections <span aria-hidden="true">☰</span></button></div><nav id="rex-primary-nav" class="portal-shell portal-nav" aria-label="Main navigation"><a href="/">Home</a>'
for name,items in navgroups:
 NAV+='<details><summary>'+name+'</summary><div class="portal-submenu">'+''.join(f'<a href="{u}">{e(t)}</a>' for t,u in items)+'</div></details>'
NAV+='<a href="/analysis/">Analysis</a><a href="/news/">News</a><a href="/economic-calendar/">Calendar</a><a href="/community/">Community</a><a href="/premium/">Premium</a></nav></header>'
footer_groups=[('Learn',[('Forex & gold','/learn/forex/'),('Crypto','/learn/crypto/'),('Glossary','/glossary/'),('Quizzes','/quizzes/'),('Article library','/articles/')]),('Explore',[('Markets','/markets/'),('Analysis','/analysis/'),('News','/news/'),('Economic calendar','/economic-calendar/'),('Tools','/tools/')]),('REX',[('About Rex','/about.html'),('Community','/community/'),('Trader’s Kit','/premium/'),('Free resources','/resources/'),('Newsletter','/newsletter/'),('Testimonials','/testimonials/')]),('Help',[('Contact','/contact/'),('FAQ','/faq/'),('Resources & providers','/partners/'),('Advertising enquiries','/advertise/'),('Referral enquiries','/affiliate/'),('Privacy','/privacy/'),('Site terms','/terms/'),('Risk disclosure','/risk-disclosure/')])]
FOOT='<footer class="portal-footer"><div class="portal-shell"><div class="footer-columns">'+''.join('<div><h2>'+t+'</h2><ul>'+''.join(f'<li><a href="{u}">{e(n)}</a></li>' for n,u in links)+'</ul></div>' for t,links in footer_groups)+'</div><p class="fine-print">© 2026 REX Trading Signal. Educational content, not personal financial advice. Trading leveraged products and cryptoassets involves risk of loss. Market data may be delayed. No course, signal or calculator guarantees a result.</p></div></footer>'
created=[]
def page(path,title,desc,body,scripts=()):
 target=ROOT/path.strip('/')/'index.html';target.parent.mkdir(parents=True,exist_ok=True)
 canonical='https://rextradingsignal.com'+path
 text='<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+e(title)+' | REX Trading Signal</title><meta name="description" content="'+e(desc)+'"><link rel="canonical" href="'+canonical+'"><meta property="og:type" content="website"><meta property="og:title" content="'+e(title)+' | REX Trading Signal"><meta property="og:description" content="'+e(desc)+'"><meta property="og:url" content="'+canonical+'"><meta property="og:image" content="https://rextradingsignal.com/assets/rex-mark.png"><link rel="icon" href="/favicon.png"><link rel="stylesheet" href="/assets/portal.css"><script async src="https://www.googletagmanager.com/gtag/js?id=G-WL6P2VP6P9"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag("js",new Date());gtag("config","G-WL6P2VP6P9");</script></head><body class="portal-page"><a class="skip-portal" href="#main">Skip to content</a>'+NAV+'<main id="main" class="portal-shell portal-main"><div class="breadcrumbs"><a href="/">Home</a><span aria-hidden="true">/</span><span>'+e(title)+'</span></div><p class="portal-eyebrow">REX TRADING SIGNAL</p><h1 class="portal-title">'+e(title)+'</h1><p class="portal-intro">'+e(desc)+'</p>'+body+'</main>'+FOOT+'<script defer src="/assets/portal.js"></script>'+''.join('<script defer src="/assets/'+x+'"></script>' for x in scripts)+'<script defer src="/assets/track.js"></script></body></html>\n'
 target.write_text(text);created.append(path)
def card(title,desc,url,label='Explore'):
 return '<article class="portal-card"><h2>'+e(title)+'</h2><p>'+e(desc)+'</p><a class="card-link" href="'+url+'">'+label+' →</a></article>'
def grid(items):return '<div class="portal-grid">'+''.join(items)+'</div>'
def note(text):return '<div class="portal-note">'+text+'</div>'
def widget(kind,url,title):return f'<div class="tv-panel"><div class="tradingview-widget-container" data-tv="{kind}"><div class="tradingview-widget-container__widget"></div><div class="tradingview-widget-copyright"><a href="{url}" target="_blank" rel="noopener">{e(title)} by TradingView</a></div></div><p class="tv-fallback">External market display. If it is unavailable or blocked, <a href="{url}" target="_blank" rel="noopener">open the provider directly</a>. Data coverage and delay depend on the instrument.</p></div>'
fxmodules=[
('Market foundations',['currency-pairs','pips-lots-and-costs','margin-and-leverage','order-types']),
('Your broker and workspace',['choosing-a-broker-like-a-business-partner','forex-scam-or-legit','forex-trading-daily-routine','how-to-use-vps-for-forex-trading']),
('Chart reading',['candlesticks-and-charts','support-resistance','moving-averages','indicators-momentum']),
('Patterns and reference levels',['fibonacci-and-patterns','what-is-price-action-trading','how-to-identify-trend-in-trading']),
('Advanced chart methods',['advanced-chart-methods','leading-and-lagging-indicators-in-a-trading-business','how-to-review-the-trend-like-a-business-owner']),
('Timeframes and market conditions',['multiple-timeframes','trading-in-volatile-markets','what-a-business-owner-does-when-the-market-goes-quiet']),
('Macro and economic events',['economic-news','central-banks-and-rates','currency-crosses-and-carry']),
('Intermarket relationships',['intermarket-and-sentiment','country-risk-and-liquidity','concentration-risk-in-your-trading-business']),
('Build and test your process',['testing-a-trading-rule','treat-trading-like-a-business','one-page-trading-business-plan-template','how-to-build-a-trading-system','trading-journal-template','how-to-think-like-a-professional-trader-mark-douglas']),
('Risk and position management',['how-to-manage-risk-in-gold-trading','position-sizing-for-gold-trading','trading-1-percent-rule','how-to-take-profit-like-a-business','how-to-scale-forex-account','why-do-most-traders-blow-their-accounts']),
('Readiness and review',['graduation-checklist','how-to-get-funded-by-a-prop-firm','what-happens-if-you-fail-a-prop-firm-challenge','how-to-run-a-weekly-review-for-your-trading-business','what-is-a-good-risk-adjusted-return'])]
cryptomodules=[(l['title'],[l['slug']]) for l in lessons if l['track']=='crypto']
course_data={}
for track,modules in [('forex',fxmodules),('crypto',cryptomodules)]:
 entries=[];body=note('Your checkmarks are stored in this browser on this device. No account is created and progress is not automatically synced. You can export a backup from <a href="/my-learning/">My learning</a>.')
 for i,(title,slugs) in enumerate(modules,1):
  rows=''
  for slug in slugs:
   l=lessonmap.get(slug) or articlemap.get(slug)
   if not l:raise ValueError('Missing lesson '+slug)
   url='/learn/lessons/'+slug+'/' if slug in lessonmap else l['url']
   entries.append(dict(id=slug,title=l['title'],url=url))
   rows+=f'<li><a href="{url}">{e(l["title"])}</a><input type="checkbox" data-complete="{slug}" aria-label="Mark {e(l["title"])} complete"></li>'
  body+=f'<details class="course-module" open><summary>{i:02d} · {e(title)}<small>{len(slugs)} '+('lesson' if len(slugs)==1 else 'lessons')+'</small></summary><ul class="lesson-list">'+rows+'</ul></details>'
 course_data[track]=entries
 body='<div class="progress-row"><progress data-progress="'+track+'" max="'+str(len(entries))+'" value="0" aria-label="Course progress"></progress><span data-progress-label="'+track+'">0 of '+str(len(entries))+' lessons completed</span></div>'+body+f'<p><a class="rex-button" href="'+('/quizzes/' if track=='forex' else '/crypto/quizzes/')+'">Check your understanding</a></p>'
 page('/learn/'+track+'/',('Forex & Gold Academy' if track=='forex' else 'Crypto Academy'),f'{len(modules)} modules and {len(entries)} lessons. Work through the concepts, practise with examples and track what you have read.',body)
(ROOT/'content/courses.json').write_text(json.dumps(course_data,ensure_ascii=False,indent=2)+'\n')
for track in ['forex','crypto']:
 seq=[l for l in lessons if l['track']==track]
 for i,l in enumerate(seq):
  body='<div class="portal-split"><article class="portal-prose">'+''.join('<p>'+e(p)+'</p>' for p in l['body'])+'<div class="portal-example"><h2>Worked example</h2><p>'+e(l['example'])+'</p></div><h2>Check your understanding</h2><p>'+e(l['exercise'])+'</p><details class="faq-item"><summary>Show explanation</summary><p>'+e(l['answer'])+'</p></details><div class="lesson-actions"><button class="rex-button" data-mark="'+l['slug']+'">Mark lesson complete</button>'
  if i+1<len(seq):body+='<a class="rex-button secondary" href="/learn/lessons/'+seq[i+1]['slug']+'/">Next lesson →</a>'
  else:body+='<a class="rex-button secondary" href="/learn/'+track+'/">Return to course</a>'
  body+='</div><p class="tools-help" data-save-status>Progress is stored on this device.</p></article><aside class="portal-card"><p class="portal-eyebrow">KEEP LEARNING</p><h2>Build the foundations.</h2><p>Work through the full course and check your understanding before moving on.</p><ul><li><a href="/learn/'+track+'/">Course outline</a></li><li><a href="'+('/glossary/' if track=='forex' else '/crypto/glossary/')+'">Look up a term</a></li><li><a href="'+('/quizzes/' if track=='forex' else '/crypto/quizzes/')+'">Take a quiz</a></li><li><a href="/tools/">Trading tools</a></li></ul></aside></div>'
  page('/learn/lessons/'+l['slug']+'/',l['title'],l['summary'],body)
for track,path in [('forex','/glossary/'),('crypto','/crypto/glossary/')]:
 subset=sorted([t for t in terms if t['track']==track],key=lambda t:t['term'].lower())
 body='<div class="search-row"><input type="search" id="glossary-search" placeholder="Find a term or definition" aria-label="Search glossary"><span id="glossary-count" role="status">'+str(len(subset))+' terms</span></div><div class="portal-chips" aria-label="Browse letters"><button class="portal-chip" data-letter="all" aria-pressed="true">All</button>'+''.join(f'<button class="portal-chip" data-letter="{c}" aria-pressed="false">{c}</button>' for c in sorted({t['term'][0].upper() for t in subset}))+'</div>'
 for t in subset:
  slug=re.sub('[^a-z0-9]+','-',t['term'].lower()).strip('-')
  body+='<section class="glossary-item" id="'+slug+'" data-letter="'+t['term'][0].upper()+'"><h2>'+e(t['term'])+'</h2><p>'+e(t['definition'])+'</p></section>'
 body+='<p id="glossary-empty" hidden>No matching terms. Try another word or choose All.</p>'
 page(path,track.title()+' glossary',str(len(subset))+' plain-language definitions. Search by term or browse alphabetically.',body)
# Quiz content: independent wording and worked explanations.
quizzes={
'forex-basics':('forex','Forex basics',[
('In EUR/USD, which is the base currency?',['EUR','USD','Both currencies'],0,'The first currency is the base. Its price is expressed in units of the quote currency.'),
('What is one pip worth for 10,000 EUR/USD units at a 0.0001 pip size?',['10 USD','1 USD','100 USD'],1,'10,000 × 0.0001 = 1 USD per pip before costs.'),
('Which order restricts execution price but may not fill?',['Market order','Any stop order','Limit order'],2,'A limit order trades only at its limit or better, but execution is not guaranteed.'),
('Does a lower margin requirement reduce the price risk of an unchanged position?',['Yes','No','Only on Mondays'],1,'Exposure and the price move determine price-move P&L; margin is collateral.'),
('What does a candle contain?',['Every transaction in order','A forecast','Open, high, low and close'],2,'OHLC summarizes the interval without revealing every intraperiod event.')]),
'risk-management':('forex','Risk management',[
('What is 1% of 10,000?',['10','100','1,000'],1,'10,000 × 0.01 = 100. This is arithmetic, not a recommended risk level.'),
('If your stop distance doubles while cash risk is fixed, approximate size should…',['Double','Stay unchanged','Halve'],2,'Risk is proportional to distance times size, before costs.'),
('After a 50% loss, what gain on the remaining capital restores the starting balance?',['50%','100%','25%'],1,'Half the capital remains. It must double to recover the original amount.'),
('Can an ordinary stop order guarantee the planned maximum loss?',['No','Yes','Only on gold'],0,'Gaps, liquidity and execution conditions can produce a worse fill.'),
('Two highly related trades each risk 50. What is their combined planned loss if both stops are hit?',['50','Zero','100'],2,'Planned risks add; a shared driver can make simultaneous losses more likely.')]),
'chart-and-system':('forex','Charts & trading systems',[
('A rising ATR primarily indicates…',['A buy signal','Larger recent ranges','A sell signal'],1,'ATR measures range magnitude, not future direction.'),
('The SMA of 8, 10 and 12 is…',['10','12','30'],0,'The simple mean is (8 + 10 + 12) / 3 = 10.'),
('Using today’s final close for a morning entry introduces…',['Diversification','Lower costs','Look-ahead bias'],2,'The final close was not known at the morning decision.'),
('Which sample is strongest for checking a rule selected on earlier data?',['The same optimized sample','Untouched later data','Only the best trades'],1,'Separate validation reduces, but does not eliminate, selection bias.'),
('Does overbought RSI guarantee an immediate reversal?',['Yes','Only at 70','No'],2,'Strong trends can remain extended; a label is not a forecast.')]),
'macro-and-execution':('forex','Macro & execution',[
('A release should be compared with…',['Only the last price','Expectations and relevant revisions','Only last year'],1,'Surprise, revisions, components and market positioning all affect interpretation.'),
('A widely expected rate hike may already be…',['Reflected in prices','Proof of a guaranteed rally','Unrelated to expectations'],0,'Price changes depend on what new information differs from prior expectations.'),
('Positive carry removes exchange-rate risk.',['True','False','Always for cross pairs'],1,'Adverse exchange-rate moves can exceed the financing benefit.'),
('For aligned price data, correlation should usually use…',['Raw nominal price levels','Ticker lengths','Returns over the same dates'],2,'Raw price levels can produce misleading relationships, particularly with trends.'),
('Course completion proves a profitable strategy.',['True','False','Only if every quiz is correct'],1,'Knowledge checks do not establish profitability or suitability for live trading.')])}
crypto_distractors=[
['Yes, because a smaller unit price means less downside.','Only if the token trades below one dollar.'],
['Yes, because a supply limit guarantees demand.','Yes, once new issuance reaches zero.'],
['Only the amount and the token price.','Only the first and last characters of the address.'],
['Yes, by reversing the published hash algorithm.','Yes, whenever the original data is short.'],
['Yes, whoever mines a block can override transaction rules.','Only the exchange receiving the transaction decides.'],
['Yes, recording it makes the statement true.','Only when the entry has more than six confirmations.'],
['Yes, if the profile uses the wallet company’s logo.','Yes, when a transfer is taking longer than expected.'],
['Yes, because no assets move immediately.','Yes, if the message comes from a familiar website.'],
['Yes, it is the total cash deposited into the asset.','Yes, but only for coins with a fixed supply.'],
['Only the current token price.','Nothing; reserves alone show the full financial position.'],
['Yes, because fraudsters never allow withdrawals.','Yes, after three successful withdrawals.'],
['Yes, a published audit guarantees the code.','Yes, if the underlying network is decentralized.'],
['Only the last traded price on any exchange.','The highest price displayed in the past hour.'],
['Yes, ownership of any token includes copyright.','Yes, if the token links to the original image.'],
['No, the share price must always equal net asset value.','Only when the underlying market is closed forever.'],
['Every address corresponds to exactly one verified person.','The metric counts only long-term asset owners.']
]
crypto_questions=[]
for i,l in enumerate(x for x in lessons if x['track']=='crypto'):
 wrong=crypto_distractors[i]
 opts=wrong[:];answer=i%3;opts.insert(answer,l['answer']);crypto_questions.append((l['exercise'],opts,answer,l['answer']))
for j,name in enumerate(['Networks & ownership','Wallet safety','Markets & products','Applications & analysis']):quizzes['crypto-'+str(j+1)]=('crypto',name,crypto_questions[j*4:(j+1)*4])
qexport={}
for slug,(track,title,qs) in quizzes.items():
 body='<form data-quiz="'+slug+'">'
 for i,(question,options,correct,explanation) in enumerate(qs):
  body+='<fieldset class="quiz-question"><legend>'+str(i+1)+'. '+e(question)+'</legend>'+''.join(f'<label><input type="radio" name="q{i}" value="{j}" required> {e(option)}</label>' for j,option in enumerate(options))+'<div class="quiz-feedback" data-feedback="'+str(i)+'" hidden></div></fieldset>'
 body+='<button class="rex-button" type="submit">Check my answers</button><button class="rex-button secondary" type="reset">Try again</button><div class="quiz-summary" role="status" aria-live="polite"></div></form>'+note('Scores are saved only in this browser. A quiz score is a learning aid, not a trading qualification.')
 page('/quizzes/'+slug+'/',title+' quiz',str(len(qs))+' questions with explanations. Answer every question, then review your results.',body)
 qexport[slug]=[dict(correct=x[2],explanation=x[3]) for x in qs]
for track,path in [('forex','/quizzes/'),('crypto','/crypto/quizzes/')]:
 page(path,track.title()+' quizzes','Test your understanding, read the explanations and revisit the lessons you need.',grid([card(title,str(len(qs))+' questions · explanations after submission','/quizzes/'+slug+'/','Start quiz') for slug,(t,title,qs) in quizzes.items() if t==track]))
(ROOT/'content/quizzes.json').write_text(json.dumps(qexport,ensure_ascii=False,indent=2)+'\n')
page('/my-learning/','My learning','Your reading progress and quiz scores on this device.',note('No sign-in or cloud account. Data stays in this browser. Export a backup before changing devices or clearing browser storage.')+'<div id="learning-dashboard"><p>Loading your saved progress…</p></div><div class="lesson-actions"><button class="rex-button" id="export-progress">Export progress</button><label class="rex-button secondary">Import progress<input id="import-progress" type="file" accept="application/json,.json" hidden></label></div><p role="status" id="progress-message"></p><noscript>Enable JavaScript to save progress. All lessons remain readable without it.</noscript>')
# Tool pages and real, local calculators.
def field(name,label,value='',kind='number',hint='',options=None):
 control='<select name="'+name+'">'+''.join(f'<option value="{v}">{e(t)}</option>' for v,t in options)+'</select>' if options else '<input name="'+name+'" type="'+kind+'" value="'+e(value)+'"'+(' step="any" required' if kind=='number' else '')+'>'
 return '<label>'+e(label)+control+('<small class="tools-help">'+e(hint)+'</small>' if hint else '')+'</label>'
def calc(slug,title,desc,fields,helptext):
 body='<div class="portal-split"><div><form class="portal-form" data-calculator="'+slug+'">'+''.join(fields)+'<button class="rex-button full" type="submit">Calculate</button></form></div><aside><div class="tool-result" id="tool-result" role="status" aria-live="polite"><h2>Your result</h2><p>Check the illustrative inputs and select Calculate.</p></div><p class="tools-help">Examples are hypothetical. Verify contract specifications, costs and conversion rates with your provider. Planned stop losses are not guaranteed execution prices.</p></aside></div><div class="portal-band"><h2>How this calculation works</h2>'+helptext+'</div><noscript>JavaScript is needed for the calculator. The formula remains available below the inputs.</noscript>'
 page('/tools/'+slug+'/',title,desc,body,['portal-math.js','portal-tools.js'])
calc('position-size','Position size calculator','Translate a cash risk budget and stop distance into lots, rounded down to the allowed lot step.',[
field('equity','Account equity',10000),field('risk','Risk budget (%)',1),field('distance','Entry-to-stop distance (quote price units)',10,hint='Gold example: 3000 to 2990 is 10. EUR/USD: 1.1000 to 1.0980 is 0.0020.'),field('contract','Base units per lot',100,hint='Gold often uses 100 oz; standard FX commonly uses 100,000 base units. Verify your contract.'),field('rate','Account currency per 1 quote currency',1,hint='For a USD account and USD quote, use 1.'),field('step','Allowed lot step',0.01),field('costs','Estimated round-trip costs per lot (account currency)',0)],'<p>Risk budget = equity × risk percentage. Cost per lot = stop distance × contract size × conversion rate + costs per lot. Divide the budget by that cost, then round down to the lot step.</p><p>Illustration: a 100 cash budget and a 10 price-unit stop on a 100-unit contract allow 0.10 lots before costs when both currencies match.</p>')
calc('pip-value','Pip value calculator','Find the cash value of a pip for your contract, size and account currency.',[field('pip','Pip size',0.0001),field('units','Base units per lot',100000),field('lots','Position size (lots)',0.1),field('rate','Account currency per 1 quote currency',1)],'<p>Pip value = pip size × base units per lot × lots × quote-to-account conversion rate.</p><p>At 0.10 lots of 100,000 units and a pip size of 0.0001, one pip is 1 quote-currency unit. Gold pip conventions vary by broker; use its actual specification.</p>')
calc('pivot-points','Pivot point calculator','Calculate reference levels from one completed period. Choose a formula and keep all inputs from the same period.',[field('high','Previous period high',110),field('low','Previous period low',90),field('close','Previous period close',100),field('open','Previous period open (used by DeMark)',100),field('method','Method',options=[('classic','Classic'),('fibonacci','Fibonacci'),('woodie','Woodie — close weighted'),('camarilla','Camarilla'),('demark','DeMark')])],'<p>Classic pivot P = (high + low + close) / 3. R1 = 2P − low; S1 = 2P − high; R2/S2 = P ± range. Other methods use different weights or range multipliers.</p><p>This Woodie variant weights the previous close twice. Verify the convention used by your platform. These are reference levels, not predictions.</p>')
calc('gain-loss','Gain, loss & recovery calculator','Measure the change in equity and the return needed to recover a loss.',[field('start','Starting equity',10000),field('end','Ending equity',8000)],'<p>Return = (ending / starting − 1) × 100%. Recovery from a loss = (starting / ending − 1) × 100%.</p><p>Falling from 10,000 to 8,000 is a 20% loss. Recovering from 8,000 to 10,000 requires 25%. External deposits and withdrawals distort this simple comparison.</p>')
calc('risk-reward','Risk / reward calculator','Compare planned price-distance risk with the distance to your target.',[field('side','Direction',options=[('long','Long / buy'),('short','Short / sell')]),field('entry','Entry price',100),field('stop','Stop price',95),field('target','Target price',110)],'<p>Reward multiple = absolute(target − entry) / absolute(entry − stop). This is a price-distance ratio before costs.</p><p>Entry 100, stop 95 and target 110 gives 2 units of planned reward for 1 unit of planned risk. A high ratio alone says nothing about the probability of reaching the target.</p>')
calc('currency-converter','Currency converter','Convert using published daily reference rates, with an optional fee estimate.',[field('amount','Amount',1000),field('base','From',options=[(x,x) for x in ['USD','EUR','GBP','JPY','AUD','CAD','CHF','NZD','SGD','THB']]),field('quote','To',options=[(x,x) for x in ['EUR','USD','GBP','JPY','AUD','CAD','CHF','NZD','SGD','THB']]),field('fee','Estimated percentage fee (%)',0)],'<p>The conversion is calculated locally using <a href="https://frankfurter.dev/">Frankfurter</a> daily reference rates. The returned date is shown with the result. These are not executable broker quotes.</p><p>Estimate after fee = amount × reference rate × (1 − fee / 100). Fixed fees and other spreads are not included.</p>')
page('/tools/currency-correlation/','Currency correlation','Compare aligned daily returns, or calculate a correlation from your own matching price series.',note('The live-data mode uses daily reference rates, not intraday broker prices. Correlation describes this sample; it is not a forecast.')+'<div data-market="correlation"><div class="data-bar"><p class="market-status" role="status">Loading daily reference data…</p><button class="rex-button secondary" data-refresh>Refresh data</button></div><div class="table-scroll" data-market-output></div></div><div class="portal-band"><h2>Use your own data</h2><p>Paste at least four prices per series, oldest first, separated by commas or whitespace. Each row must represent the same timestamp in both series.</p><form class="portal-form" data-calculator="correlation"><label>Series A<textarea name="a" rows="4" required placeholder="100, 102, 101, 104, 103"></textarea></label><label>Series B<textarea name="b" rows="4" required placeholder="80, 81, 80, 83, 82"></textarea></label><button type="submit" class="rex-button">Calculate correlation</button></form><div id="tool-result" class="tool-result" role="status"><p>Your Pearson correlation of period returns will appear here.</p></div></div>',['portal-math.js','portal-tools.js','portal-markets.js'])
page('/tools/market-hours/','Forex market hours','See conventional trading-session windows in your timezone, with daylight-saving adjustments.', '<label>Display timezone <select id="session-zone">'+''.join(f'<option value="{z}">{label}</option>' for z,label in [('local','Your device timezone'),('UTC','UTC'),('Asia/Ho_Chi_Minh','Vietnam'),('Europe/London','London'),('America/New_York','New York'),('Asia/Tokyo','Tokyo'),('Australia/Sydney','Sydney')])+'</select></label><p id="session-now" class="market-status" role="status"></p><div id="sessions" class="portal-grid"></div>'+note('Windows: Sydney 08:00–17:00, Tokyo 09:00–18:00, London 08:00–17:00 and New York 08:00–17:00 in each city’s local time. The broad FX week is Sunday 17:00 to Friday 17:00 New York time. These are conventional session guides, not exchange or broker opening guarantees; holidays and product breaks are not included.'),['portal-tools.js'])
calc('risk-on-risk-off','Risk appetite worksheet','A manual scenario check across three market observations. Enter changes over the same period.',[field('stocks','Broad equity index change (%)',0),field('vix','Volatility index change (%)',0),field('spreads','Credit spread change (basis points)',0)],'<p>This is a manual breadth score, not a live sentiment feed or the BabyPips meter. Stocks rising, volatility falling and credit spreads narrowing each contribute +1. Opposite moves contribute −1; unchanged contributes 0.</p><p>Score = sum / 3 × 100. Equal weights and directional signs are a deliberately simple worksheet. Divergent signals are common and the score does not recommend a trade.</p>')
toolinfo=[('position-size','Position size','Work backward from the cash you plan to risk.'),('pip-value','Pip value','Translate a pip into your account currency.'),('pivot-points','Pivot points','Classic, Fibonacci, Woodie, Camarilla and DeMark.'),('gain-loss','Gain, loss & recovery','Understand the arithmetic of a drawdown.'),('risk-reward','Risk / reward','Compare your planned stop and target.'),('currency-converter','Currency converter','Daily reference rates with a fee estimate.'),('currency-correlation','Currency correlation','Aligned daily returns and your own datasets.'),('market-hours','Market hours','Local session windows with daylight-saving handling.'),('risk-on-risk-off','Risk appetite worksheet','Compare your own cross-market observations.'),('regulators','Regulator directory','Find official registers and verify a legal entity.')]
page('/tools/','Trading tools','Calculate exposure, check costs and prepare your trading day.',grid([card(t,d,'/tools/'+s+'/','Open tool') for s,t,d in toolinfo]))
# Market pages.
market_info=[('forex','Forex snapshot','Daily reference quotes, changes and pair statistics.'),('currency-strength','Currency strength','Equal-weight one-day performance against the other seven currencies.'),('volatility','Currency volatility','Standard deviation of recent daily returns, with the sample stated.'),('movers','Top forex movers','The strongest and weakest changes in the tracked pair list.'),('heatmap','Forex heatmap','One-day changes across the eight-currency matrix.'),('crypto','Crypto snapshot','Prices and statistics from an external crypto market display.'),('crypto-strength','Crypto strength','Compare and sort percentage changes in the crypto screener.'),('crypto-volatility','Crypto volatility','Sort volatility and performance across crypto trading pairs.'),('crypto-heatmap','Crypto heatmap','A provider heatmap of cryptoasset performance and market size.')]
for slug,title,desc in market_info:
 if slug.startswith('crypto'):
  body=note('External TradingView display. Select the performance or volatility columns and sort them to compare assets. This is a third-party screener, not a proprietary REX strength index. Coverage, refresh and delay depend on the provider.')+widget('crypto-heatmap' if slug=='crypto-heatmap' else 'crypto' if slug!='crypto-volatility' else 'crypto-volatility','https://www.tradingview.com/markets/cryptocurrencies/','Crypto markets')
  scripts=['portal-widgets.js']
 else:
  body=note('Source: <a href="https://frankfurter.dev/">Frankfurter</a> daily reference rates. No intraday ticks. The effective dates and sample size are shown after loading. Rates are for comparison, not execution.')+f'<div data-market="{slug}"><div class="data-bar"><p class="market-status" role="status">Loading daily reference data…</p><button class="rex-button secondary" data-refresh>Refresh data</button></div><div class="table-scroll" data-market-output></div></div><details class="faq-item"><summary>Calculation methodology</summary><p>Currency strength is the mean percentage change versus the other seven currencies from the previous available observation. Pair changes use the last two available observations. Volatility is the sample standard deviation of up to 30 daily simple returns, expressed as a daily percentage; it is not ATR or annualized volatility. Weekends and missing publication days are omitted. Cross rates are derived from a shared USD base.</p></details>'
  scripts=['portal-math.js','portal-markets.js']
 page('/markets/'+slug+'/',title,desc,body+grid([card(t,d,'/markets/'+s+'/') for s,t,d in market_info if s!=slug][:3]),scripts)
page('/markets/','Market overview','Start with gold and the major markets, then compare currencies and cryptoassets.',widget('overview','https://www.tradingview.com/markets/','Market overview')+grid([card(t,d,'/markets/'+s+'/') for s,t,d in market_info]),['portal-widgets.js'])
page('/economic-calendar/','Economic calendar','Review scheduled releases, their importance and the published actual, forecast and previous values.',note('Times and filters are controlled inside the calendar. Check its selected timezone before planning a trade. The calendar is supplied by TradingView; values may be revised or delayed.')+widget('calendar','https://www.tradingview.com/economic-calendar/','Economic calendar')+grid([card('Read the release','Learn how expectations and revisions affect interpretation.','/learn/lessons/economic-news/'),card('Session hours','Check the trading windows in your timezone.','/tools/market-hours/'),card('Plan the risk','Calculate size before an event changes conditions.','/tools/position-size/')]),['portal-widgets.js'])
page('/news/','Market news','External market headlines alongside a practical framework for reading economic events.',widget('news','https://www.tradingview.com/news/','Market news')+grid([card('Economic releases','Actual, forecast and previous are different pieces of information.','/learn/lessons/economic-news/'),card('Policy expectations','Read the decision and the expected path separately.','/learn/lessons/central-banks-and-rates/'),card('Rex’s latest articles','Read the latest educational posts from the daily notebook.','/articles/')]),['portal-widgets.js'])
page('/analysis/','Gold & market analysis','Use the chart to explore the market, then apply a documented decision process.',widget('gold-chart','https://www.tradingview.com/symbols/XAUUSD/','Gold chart')+grid([card('Price action','Build a repeatable definition before looking for a setup.','/what-is-price-action-trading.html'),card('Volatility','Adapt exposure when the price of risk changes.','/trading-in-volatile-markets.html'),card('Trade ideas','See where Rex publishes gold setups with their reasoning.','/trading/trade-ideas/')]),['portal-widgets.js'])
category_rules={'technical-analysis':('Technical analysis',['trend','price-action','indicator','volatile','profit','open-trade']), 'psychology':('Trading psychology',['psychology','fomo','missed','knowing','douglas','blow','stop-trading']), 'systems':('Trading systems',['system','routine','journal','automate','ea-on','business-model','checklist','weekly-review'])}
page('/trading/','Trading library','Explore the market process through analysis, systems, psychology and trade planning.',grid([card(t,'A curated selection from the Rex notebook.','/trading/'+s+'/') for s,(t,_) in category_rules.items()]+[card('Trade ideas','Gold setups and a repeatable planning checklist.','/trading/trade-ideas/'),card('Crypto guides','Network, custody and market concepts for beginners.','/crypto/guides/'),card('All articles','Browse and search the complete daily notebook.','/articles/')]))
for slug,(title,keywords) in category_rules.items():
 selected=[a for a in articles if any(k in a['url'] for k in keywords)]
 page('/trading/'+slug+'/',title,'Educational articles from the Rex notebook. Dates belong to the original publications.',grid([card(a['title'],a['desc'],a['url'],'Read article') for a in selected]))
page('/trading/trade-ideas/','Trade ideas','Gold setups are published in Rex’s Telegram channel. Use the checklist to understand a plan before acting.', '<div class="portal-band"><h2>Follow the original setup</h2><p>The channel contains the original post and subsequent updates. This page does not invent entry prices or present an old setup as current.</p><a class="rex-button" href="'+TG+'">Open Rex’s gold channel</a></div><div class="portal-prose"><h2>A complete plan answers five questions</h2><ol><li>Which instrument and timeframe does the idea cover?</li><li>What condition triggers an entry?</li><li>Where is the idea invalidated?</li><li>How much cash is at risk after costs?</li><li>What ends the trade or makes the plan expire?</li></ol></div>'+grid([card('Calculate size','Translate a plan into a defined exposure.','/tools/position-size/'),card('Check the calendar','Know which scheduled events may affect execution.','/economic-calendar/'),card('Record the decision','Keep the original reasoning beside the outcome.','/trading-journal-template.html')]))
page('/crypto/guides/','Crypto guides','Original introductions to crypto networks, custody, products and common risks.',grid([card(l['title'],l['summary'],'/learn/lessons/'+l['slug']+'/','Read guide') for l in lessons if l['track']=='crypto']))
# Existing community and paid offers, without inventing authentication or member claims.
page('/community/','The Rex community','Follow the free gold channel and find the existing routes to Rex’s members’ room.',grid([card('Free Telegram channel','Read original gold setups, their reasoning and subsequent updates.',TG,'Open Telegram'),card('The Operators’ Room','The private room is included in the existing Trader’s Business Kit. Review the tiers before buying.','/premium/','View the Kit'),card('Questions for Rex','Use the established contact to ask about access or the learning resources.',CONTACT,'Contact Rex')])+note('Discussion and membership currently take place on Telegram. This website does not yet host a separate forum or a cross-device account system.')+'<div class="portal-band"><h2>Useful community habits</h2><ul><li>Include the instrument, timeframe and reasoning when discussing a setup.</li><li>Share learning points from losing trades as well as winning ones.</li><li>Never share passwords, recovery phrases or account access.</li><li>Check the original source of any forwarded message.</li></ul></div>')
page('/premium/','The Trader’s Business Kit','Explore Rex’s existing one-time Kit and support tiers.',grid([card('General · $9','The book, one-page plan, Operators’ Room and future Kit updates. One-time payment.','/#kit','Read full terms'),card('VIP · $29','General plus the existing monthly group Q&A and Week Ahead offering. One-time payment.','/#kit','Read full terms'),card('Very VIP · $49','VIP plus the existing onboarding account health check and priority support offering. One-time payment.','/#kit','Read full terms')])+note('The full inclusions, refund terms and availability remain on the <a href="/#kit">original offer</a>. These are the existing REX products; no new subscription or paid course is created here.'))
page('/resources/','Free trading resources','Put the learning into a written plan and a repeatable review.',grid([card('Trader’s Business Plan','Get the existing free plan through Rex’s resource page.','/business-plan/','Get the plan'),card('Journal template','Learn which fields to record and how to review them.','/trading-journal-template.html','Read the guide'),card('Trading rules checklist','Turn your process into a set of decisions you can audit.','/trading-rules-checklist.html','Read the checklist'),card('Calculators','Size positions and evaluate risk in clear units.','/tools/','Open tools')]))
page('/newsletter/','Rex updates & the free plan','Use the existing email signup to request the Trader’s Business Plan.', '<div class="portal-band"><h2>Start with the free resource</h2><p>The signup form on the resource page explains what you are requesting. Delivery and follow-up use Rex’s existing email service.</p><a class="rex-button" href="/business-plan/">Open the signup form</a></div><p>For gold setup updates, visit the <a href="'+TG+'">Telegram channel</a>.</p>')
page('/testimonials/','Member experiences','Watch the existing member videos and hear their experiences in their own words.', '<div class="portal-grid">'+''.join(f'<figure class="portal-card"><video controls playsinline preload="none" poster="/videos/{p}.jpg" style="width:100%;aspect-ratio:464/848"><source src="/videos/{v}.mp4" type="video/mp4"></video><figcaption>{name}</figcaption></figure>' for p,v,name in [('review-andrea-poster','review-andrea','Andrea · member'),('review-member-3months-poster','review-member-3months','Platinum member · 3 months in'),('review-member-poland-poster','review-member-poland','Member · Poland')])+'</div>'+note('Individual experiences are not promises of future results. Trading involves risk.'))
page('/contact/','Contact Rex','Use the existing contact for access, resources and website questions.', '<div class="portal-band"><h2>Message Rex on Telegram</h2><p>Contact: @Rextrading_gold. Describe the resource or access issue and include its page link. Do not send account passwords or wallet recovery material.</p><a class="rex-button" href="'+CONTACT+'">Open the contact</a></div>'+grid([card('Frequently asked questions','Find answers about learning, data and access.','/faq/'),card('Free resources','Get the plan and explore the journal guide.','/resources/')]))
faqs=[('Is the academy free?','The courses, glossary, quizzes and calculators added here are free to read and use. The existing Trader’s Business Kit has its own paid tiers and terms.'),('Does the site provide an account login?','Not currently. Learning progress is saved in this browser on this device. Use My learning to export or import a backup. Telegram access is managed separately.'),('Where are the trade setups?','The original gold setup posts and updates are in Rex’s free Telegram channel. Educational examples on the website are not current trade calls.'),('Are currency rates real-time?','The REX forex comparison tables use daily reference rates with effective dates shown. TradingView displays have their own coverage and delays. Neither should be assumed to match your broker’s executable quote.'),('Why is a market display blank?','A data provider may be unavailable, rate-limited or blocked by browser settings. Use the provider link below the display. The site does not fill gaps with invented prices.'),('Do calculators include every cost?','No. Check each formula and input. Spreads, commissions, financing, currency conversion and slippage can affect the actual outcome.'),('Can I sync progress across devices?','There is no automatic account sync. Export a JSON backup in My learning and import it on the other device. Anyone with that backup can see the included progress and quiz scores.'),('Is a quiz score a trading qualification?','No. It checks understanding of a small set of concepts and is not evidence of a profitable strategy or suitability for live trading.'),('Is Rex affiliated with BabyPips?','No affiliation is claimed. Rex’s content and products are its own. The site’s educational structure was inspired by common trading-learning resources.'),('What are the Kit refund terms?','Read the original Kit section on the homepage. General, VIP and Very VIP have their existing terms; this portal does not replace them.'),('How do I report an error?','Send Rex the page link, the input values if a calculator is involved, and a short explanation through the Contact page.')]
page('/faq/','Frequently asked questions','Learning, data, tools and membership explained.', ''.join('<details class="faq-item"><summary>'+e(q)+'</summary><p>'+e(a)+'</p></details>' for q,a in faqs))
regulators=[('United States · NFA BASIC','https://www.nfa.futures.org/basicnet/','Search registrations and disciplinary information for the exact firm or individual.'),('United Kingdom · FCA Register','https://register.fca.org.uk/','Check the legal entity, permissions and contact details against the register.'),('Australia · ASIC registers','https://asic.gov.au/online-services/search-asics-registers/','Find the relevant company and financial-services licensing records.'),('Singapore · MAS directory','https://eservices.mas.gov.sg/fid','Check the entity and the activities for which it is licensed.'),('Cyprus · CySEC','https://www.cysec.gov.cy/','Use the regulator’s entity lists and warnings.'),('US derivatives · CFTC','https://www.cftc.gov/','Review investor education and official notices.')]
page('/tools/regulators/','Regulator directory','Start with the official register for the firm’s legal entity and your jurisdiction.',grid([card(t,d,u,'Open official source') for t,u,d in regulators])+note('Registration is not a guarantee of investment performance. Check exact names, domains, permissions and warnings. A brand may operate through different legal entities in different countries.'))
page('/partners/','Resources & data providers','The external services used or referenced by the Rex learning portal.',grid([card('TradingView','Charts, market displays, headlines and the economic-calendar widget.','https://www.tradingview.com/','Visit provider'),card('Frankfurter','Daily exchange-rate reference data for currency comparisons and conversion.','https://frankfurter.dev/','Read data documentation'),card('Official registers','Links to public regulator databases.','/tools/regulators/','Browse registers')])+note('Listing a provider is attribution, not a claim of sponsorship, partnership or endorsement. Rex’s existing broker-commission disclosure remains on the homepage.'))
page('/advertise/','Advertising enquiries','Contact Rex to discuss a proposed placement or collaboration.', '<div class="portal-prose"><p>Send the organization’s name, the product, the intended audience and the proposed placement. Rex can review the request before any agreement or publication.</p><p>No advertising package, affiliate rate or endorsement is promised on this page.</p><a class="rex-button" href="'+CONTACT+'">Contact Rex</a></div>')
page('/affiliate/','Referral enquiries','Ask Rex about an existing referral arrangement before sharing an offer.', '<div class="portal-prose"><p>This website does not publish a new affiliate program, commission schedule or tracking agreement. If you want to refer readers to Rex, contact Rex to clarify the arrangement and the disclosures that would apply.</p><a class="rex-button" href="'+CONTACT+'">Contact Rex</a></div>')
page('/privacy/','Privacy information','How this static website and its connected features handle information.', '<div class="portal-prose"><h2>Learning progress</h2><p>Completed lessons and quiz scores are stored in your browser’s local storage. They are not sent to a REX account service. Clearing site data removes that local copy. Export files contain your progress and scores.</p><h2>Analytics and external displays</h2><p>The site uses its existing Google Analytics tag. TradingView widgets and reference-rate requests contact external services, which receive ordinary connection information such as an IP address. Their own privacy policies apply.</p><h2>Email and Telegram</h2><p>The free-plan forms send the email address you enter to Rex’s existing subscription service. Telegram links open Telegram, where its policies and the channel’s practices apply. Do not enter sensitive account information in a signup form.</p><h2>Questions or requests</h2><p>Contact Rex through the <a href="/contact/">Contact page</a> for questions about email subscriptions or personal information. No retention period beyond the existing service’s practices is asserted here.</p></div>')
page('/terms/','Site terms & use','Use the educational material and tools with an understanding of their limits.', '<div class="portal-prose"><h2>Educational purpose</h2><p>Articles, lessons, examples and calculator outputs are general learning resources. They are not individualized financial advice, promises of return or instructions to enter a trade.</p><h2>Data and calculations</h2><p>Verify instrument specifications and external data before relying on a result. Information can be delayed, incomplete or revised. Hypothetical examples are not an investment track record.</p><h2>Existing paid products</h2><p>The Trader’s Business Kit retains the inclusions, prices and refund terms shown on its <a href="/#kit">original offer</a>. This page creates no new subscription or payment agreement.</p><h2>External services</h2><p>External websites and embedded tools operate under their own terms. Provider attribution does not imply an endorsement or affiliation.</p><h2>Contact</h2><p>Report errors or ask about intended use through the <a href="/contact/">Contact page</a>.</p></div>')
page('/risk-disclosure/','Risk disclosure','Understand what the educational content and planned-risk calculations cannot promise.', '<div class="portal-prose"><p>Trading gold, forex, leveraged products and cryptoassets can result in substantial losses. Some products or arrangements can expose you to losses beyond an initial margin deposit. Protections depend on the product, provider and jurisdiction.</p><p>Stops may execute at different prices during gaps, fast markets or limited liquidity. A calculated risk budget is a plan, not a guarantee. Past performance and individual testimonials do not establish future results.</p><p>Rex does not manage your account through these pages. The existing channel is supported by a broker-paid introducing commission as disclosed on the homepage. Consider costs, counterparty risk and whether you understand the product before making any decision.</p></div>')
# Update existing navigation without touching the daily-publisher cards or article copy.
for p in list(ROOT.glob('*.html'))+[ROOT/'articles/index.html']:
 if p.name=='index-improved.html':continue
 s=p.read_text()
 if not re.search(r'<header class="(?:portal-header|site-header|topbar|top)"',s):continue
 s=re.sub(r'<header class="(?:portal-header|site-header|topbar|top)".*?</header>',lambda m:NAV,s,count=1,flags=re.S)
 if '/assets/portal.css' not in s:s=s.replace('</head>','<link rel="stylesheet" href="/assets/portal.css">\n</head>')
 if '/assets/portal.js' not in s:s=s.replace('</body>','<script defer src="/assets/portal.js"></script>\n</body>')
 if p.name=='index.html' and p.parent==ROOT:
  s=s.replace('href="/#learn"','href="/learn/forex/"').replace('href="#learn"','href="/learn/forex/"')
  section='<section class="portal-home-additions" id="explore-portal"><div class="portal-shell"><p class="portal-eyebrow">YOUR TRADING WORKSPACE</p><h2>Learn. Prepare. Review.</h2>'+grid([card('Forex & gold academy','A structured course with lessons and progress tracking.','/learn/forex/'),card('Crypto academy','Networks, custody, products and risks explained.','/learn/crypto/'),card('Market overview','Gold charts, currency comparisons and crypto displays.','/markets/'),card('Economic calendar','Check scheduled releases before the trading day.','/economic-calendar/'),card('Trading tools','Position sizing, pip value, recovery and more.','/tools/'),card('Quizzes & glossary','Check your understanding and look up unfamiliar terms.','/quizzes/')])+'</div></section>'
  if 'id="explore-portal"' not in s:s=s.replace('<section class="learning-section"',section+'<section class="learning-section"',1)
  if '<footer class="portal-footer">' in s:s=re.sub(r'<footer class="portal-footer">.*?</footer>',lambda m:FOOT,s,count=1,flags=re.S)
  else:s=s.replace('</main><footer>','</main>'+FOOT+'<footer>',1)
 p.write_text(s)
# Index new routes for search engines; retain every existing URL.
sitemap=ROOT/'sitemap.xml';old=sitemap.read_text();newurls=''
for path in created:
 url='https://rextradingsignal.com'+path
 if '<loc>'+url+'</loc>' not in old:newurls+='  <url><loc>'+url+'</loc><lastmod>2026-09-15</lastmod></url>\n'
sitemap.write_text(old.replace('</urlset>',newurls+'</urlset>'))
(ROOT/'content/portal-routes.json').write_text(json.dumps(created,indent=2)+'\n')
print('Generated',len(created),'routes;',len(course_data['forex']),'forex lessons;',len(course_data['crypto']),'crypto lessons;',len(terms),'terms;',len(quizzes),'quizzes.')
